### ISSUE TITLE
您好，我在准备数学建模，我看了你们的数模之星论文，粒子群算法你们是参考的哪个代码啊，可以发我一下吗，非常感谢，联系方式：13873062122

### ISSUE THREAD

**Issue by lilepinghe** [DongZhouGu/MathModel-Pretrain#10]

**Comment by DongZhouGu** [comment]
主要使用的Python的scikit-opt库
[智能启发算法scikit-opt库](https://github.com/guofei9987/scikit-opt)以及[作者博客](https://www.guofei.site/)

**Comment by lilepinghe** [comment]
大佬您好，我看了你分享的博客，博客解决的问题比较简单，好像没有和数学建模这类问题对应起来，我看了你们的第四问的代码，有一些不懂的地方，比如这个函数def func_transformer(func):，大佬你第四问，还参照了哪些源码啊？谢谢大佬

**Comment by DongZhouGu** [comment]
就是scikit-opt库的源码，仔细看下。[func_transformer函数](https://github.com/guofei9987/scikit-opt/blob/master/sko/tools.py)

**Comment by lilepinghe** [comment]
您好，首先感谢您的回答，打扰您了，方便的话可以（有偿）提供第四问代码的Excel表格吗

**Comment by lilepinghe** [comment]
您好，因为我在看代码的过程中，有时候看到这种molecular_des_corr_del_describe，不知道这个Excel是什么

**Comment by lilepinghe** [comment]
大哥您好，有时间的话可以联系一下我吗，真的非常感谢

**Comment by DongZhouGu** [comment]
[molecular_des_corr_del_describe.csv](https://pan.baidu.com/s/1u1mHeMs0JJS8RlmaFeR2hA?pwd=6ev7)，就是题目给的excel，只是特征数量减少了

**Comment by lilepinghe** [comment]
大佬，首先感谢您的回答，最近一直在学习你们的论文，也学到了很多，可以提供一下代码和数据吗？我的邮箱是1693522484@qq.com，万分感谢!

**Comment by DongZhouGu** [comment]
[已上传](https://github.com/DongZhouGu/MathModel-Pretrain/tree/master/%E6%95%B0%E6%A8%A1%E4%B9%8B%E6%98%9F/%E6%8F%90%E4%BA%A4%E9%99%84%E4%BB%B6/%E4%BB%A3%E7%A0%81%E4%B8%8E%E4%B8%AD%E9%97%B4%E7%BB%93%E6%9E%9C)
