### ISSUE TITLE
求大佬一等奖论文和代码

### ISSUE THREAD

**Issue by harmony666** [DongZhouGu/MathModel-Pretrain#8]
哥们，你们readme里面待办事项的第一条，上传你们一等奖的优秀论文和代码，啥时候传呢？求求你们了

**Comment by DongZhouGu** [comment]
[已上传]( https://github.com/DongZhouGu/MathModel-Pretrain/tree/master/%E6%95%B0%E6%A8%A1%E4%B9%8B%E6%98%9F)
代码论文最后有
