### ISSUE TITLE
请问哪里可以找到《抗乳腺癌候选药物的优化建模》的源码

### ISSUE THREAD

**Issue by Rudeguy1** [DongZhouGu/MathModel-Pretrain#9]
你好，看了你的优秀论文学习到了很多，想要尝试复现你用过的方法，发现你的class MulitiPrototypicalNet3 类里有些方法没有给出，

可以分享一下这个类的源码地址我去学习一下嘛

**Comment by xiao-aBoy** [comment]
已上传！
位置：数模之星/提交附件/代码与中间结果

**Comment by Rudeguy1** [comment]
非常非常非常感谢。

**Comment by Rudeguy1** [comment]
非常非常荣幸能够收到你的回复。
感谢你的分享，真的帮助了我很多。
谢谢谢谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月24日(星期六) 晚上10:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DongZhouGu/MathModel-Pretrain] 请问哪里可以找到《抗乳腺癌候选药物的优化建模》的源码 (Issue #9)





 
已上传！
 位置：数模之星/提交附件/代码与中间结果

**Comment by xiao-aBoy** [comment]
加油加油

**Comment by xiao-aBoy** [comment]
已上传到仓库
Rudeguy1 ***@***.***> 于2022年9月13日周二 19:29写道：
